from enum import StrEnum


class UserRole(StrEnum):
    RECRUITER = "RECRUITER"
    ADMIN = "ADMIN"


class OperationStatus(StrEnum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class OperationType(StrEnum):
    LOGIN = "LOGIN"
    CREATE_USER = "CREATE_USER"
    CHANGE_USER_ROLE = "CHANGE_USER_ROLE"
    BLOCK_USER = "BLOCK_USER"
    EXTRACT_RESUME = "EXTRACT_RESUME"
    GENERATE_RESUME = "GENERATE_RESUME"
    CREATE_PARTNER = "CREATE_PARTNER"
    UPDATE_PARTNER = "UPDATE_PARTNER"
    UPLOAD_TEMPLATE = "UPLOAD_TEMPLATE"
    ACTIVATE_TEMPLATE = "ACTIVATE_TEMPLATE"
